### ISSUE TITLE
Screenshots taken starting one line too late?

### ISSUE THREAD

**Issue by xdanieldzd** [Rinnegatamante/Screenie#1]
Tried the plugin, works well aside from one issue: It appears to take screenshots starting one scanline too late. That causes shots from, for example, Disgaea 4: A Promise Revisited to have one garbage line, and ones from Puyo Puyo Tetris to have the missing first line (or its equivalent from a different framebuffer, not sure how the Vita works here) at the bottom.

Disgaea 4 title screenshots via the official feature vs Screenie:
![Official](https://cloud.githubusercontent.com/assets/7199225/25557812/e6a16510-2d19-11e7-9a0f-1f2a298a58fe.jpg)
![Screenie](https://cloud.githubusercontent.com/assets/7199225/25557817/eea1e85c-2d19-11e7-8cec-6f2d4b2a54f9.png)

**Comment by Rinnegatamante** [comment]
It's probably related to this since Screenie uses the same code: https://github.com/Rinnegatamante/rinCheat/issues/16

Looking for a solution.

**Comment by Rinnegatamante** [comment]
@xdanieldzd Can you try if this solve the issue? https://rinnegatamante.it/Screenie.suprx

**Comment by xdanieldzd** [comment]
Yup, looks like that build fixes it! Have only tested Disgaea 4 so far, but it now appears to start at the correct line and the garbage line at the bottom is gone:

![pcsb00455-2017-4-30-13-5-32](https://cloud.githubusercontent.com/assets/7199225/25563881/35cca384-2da6-11e7-8364-877e42eddfca.png)

**Comment by Rinnegatamante** [comment]
Solved with https://github.com/Rinnegatamante/Screenie/commit/0f6269b0c539ef1222e2d0bce0ba662ca542fcf9
