### ISSUE TITLE
Right side black band analysis

### ISSUE THREAD

**Issue by Rinnegatamante** [Rinnegatamante/Screenie#2]
I supposed that the black band showing on right side is not always showed the same way on several apps. Needs more testing. If confirmed to be ALWAYS on right side, a patch can be done for the plugin to remove it.

Needs reports with screenshots of as much games/apps as possible to check this.

**Comment by Rinnegatamante** [comment]
Game: Digimon Story Cyber Sleuth [PCSB00861]
Resolution: 1024x544
Black Band: Present (Right Side)
![dgmn](https://cloud.githubusercontent.com/assets/9152710/25563946/05ceb8a0-2da8-11e7-93ef-f5e0038c0cdd.jpg)

**Comment by Rinnegatamante** [comment]
Game: Minecraft [PCSE00491]
Resolution: 768x408
Black Band: Present (Right Side)
![mine](https://cloud.githubusercontent.com/assets/9152710/25563976/c88f65a6-2da8-11e7-8143-1a2487bb7cf1.jpg)

**Comment by xdanieldzd** [comment]
Disgaea 4: A Promise Revisited - 1024x544, black band present (right side)
(Screenshot see issue #1)

Hyperdimension Neptunia ReBirth 2 - 1024x544, right side
![pcsb00626-2017-4-30-13-27-6](https://cloud.githubusercontent.com/assets/7199225/25564011/b83477cc-2da9-11e7-85af-9ca5576e092b.png)

Hyperdimension Neptunia U - 1024x544, right side
![pcsb00710-2017-4-30-13-29-4](https://cloud.githubusercontent.com/assets/7199225/25564016/cbfe6f38-2da9-11e7-890f-9cdbb190197a.png)

Dengeki Bunko Fighting Climax - 960x544, no band
![pcsb00763-2017-4-30-13-28-10](https://cloud.githubusercontent.com/assets/7199225/25564024/daa79e42-2da9-11e7-806e-35d2e282fac8.png)

Sayonara Umihara Kawase+ - 1024x544, right side
![pcsb00782-2017-4-30-13-26-1](https://cloud.githubusercontent.com/assets/7199225/25564028/e8df7a7a-2da9-11e7-9ed9-d12488d1f0dc.png)

Puyo Puyo Tetris - 1024x544, right side
![pcsg00224-2017-4-30-13-25-17](https://cloud.githubusercontent.com/assets/7199225/25564031/05650eee-2daa-11e7-993d-6a34667daa12.png)

**Comment by HitchensRIP** [comment]
Lunar (via Adrenaline) - 1024x544, right side
![npxs10028-2017-4-30-20-20-52](https://cloud.githubusercontent.com/assets/28229862/25566863/bdc19cb8-2de2-11e7-9583-1f002bdfbfe5.png)

Dragon Quest Builders - 1024x544, right side
![pcse00912-2017-4-30-20-15-20](https://cloud.githubusercontent.com/assets/28229862/25566828/ea2c21b6-2de1-11e7-80e8-b314bd3056b3.png)
God Eater Resurrection - 1024x544, right side
![pcsb00874-2017-4-30-20-8-11](https://cloud.githubusercontent.com/assets/28229862/25566799/80ca3c3a-2de1-11e7-87f0-d0b11b3b5f9c.png)

**Comment by K4thos** [comment]
Game: Metal Gear Solid HD [PCSB00118]
Resolution: 1024x544
Black Band: Present (Right Side)
![pcsb00118-2017-5-1-18-59-52](https://cloud.githubusercontent.com/assets/8928195/25587153/1395fb14-2ea3-11e7-8cff-ebcebcf6b136.png)

Game: NFS Most Wanted [PCSB00183]
Resolution: 960x544
Black Band: No (native)
![pcsb00183-2017-5-1-19-9-17](https://cloud.githubusercontent.com/assets/8928195/25587191/39a3ae0a-2ea3-11e7-95d9-be51f84f32b0.png)

Game: Terraria [PCSE00317]
Resolution: 960x544
Black Band: No (native)
![pcse00317-2017-5-1-18-53-44](https://cloud.githubusercontent.com/assets/8928195/25587220/59535df4-2ea3-11e7-9032-f76187ffb36c.png)

**Comment by Rinnegatamante** [comment]
Well, it seems it's always on same spot, i'll proceed for a patch. A new version of Screenie should came today or tomorrow.

**Comment by K4thos** [comment]
check out previous comment (posted a minute before yours) ;) I will check some more retail games in a minute.

**Comment by HitchensRIP** [comment]
There's absolutely no way to reduce the freezing time i assume ?

In RPGs it's totally fine but in action games it makes it impossible to take screens..

**Comment by Rinnegatamante** [comment]
The freezing time is related to kuio. Kernel Plugins have stack limitation that's why it's actually that slow, i'm thinking about some improvements that should make it a lot faster during screenshot acquisition.

**Comment by K4thos** [comment]
Game: Persona 4 GOLDEN [PCSB00245]
Resolution: 1024x544
Black Band: Present (Right Side)
![pcsb00245-2017-5-1-20-11-11](https://cloud.githubusercontent.com/assets/8928195/25589187/e58ee0ce-2eab-11e7-9997-84db939010ab.png)

Game: Dragon's Crown [PCSB00408]
Resolution: 1024x544
Black Band: Present (Right Side)
![pcsb00408-2017-5-1-19-42-27](https://cloud.githubusercontent.com/assets/8928195/25589218/121c24bc-2eac-11e7-8d13-cda0da0291b3.png)

Game: Wipeout 2048 [PCSF00007
Resolution: 960x544
Black Band: No (native)
![pcsf00007-2017-5-1-20-7-35](https://cloud.githubusercontent.com/assets/8928195/25589246/2c682226-2eac-11e7-8816-e2219fdd9b92.png)
]

Game: Killzone Mercenary [PCSF00243
Resolution: 960x544
Black Band: No (native)
![pcsf00243-2017-5-1-19-59-14](https://cloud.githubusercontent.com/assets/8928195/25589268/4684bc46-2eac-11e7-8ca0-e12477ca1d31.png)

----------

yep, looks like it's always either on the right side and in some games there is no black band at all.

**Comment by K4thos** [comment]
one question - does the plugin capture the screen before or after rescaling takes place? That Minecraft screen seems to indicate that it's the former (768x408) but up until now I thought NFS Most Wanted was running at sub-native res. The screenshot is at 960x544 though.

**Comment by Rinnegatamante** [comment]
The plugin captures the raw framebuffer. Certain games just set the game on internal lower resolution that is upscaled by vita hardware. An example is Minecraft. Framebuffer can be set at three different internal res: 480x272, 720x408, 960x544.

**Comment by Rinnegatamante** [comment]
Adjusted with https://github.com/Rinnegatamante/Screenie/commit/ae990e8a8fb0a3c15aa37967ceb8fb5a99e88efb
