### ISSUE TITLE
Replace and hook the screenshot button with the default PSV one.

### ISSUE THREAD

**Issue by alpakeno** [Rinnegatamante/Screenie#3]
PSV take screenshot when pressing Home+Start, so can Screenie hook and use these button to take screenshot instead.

**Comment by Rinnegatamante** [comment]
Home button can't be detected in userspace. That's why Screenie uses a different combination.

**Comment by alpakeno** [comment]
So what about making Screenie running on kernel? is that currently possible?

**Comment by Rinnegatamante** [comment]
Making it a kernel plugin is a possibility but for the moment i'm experimenting a bit with sceScreenshot and see if i can get it to use the standard buttons combo even in userspace.
